name: benchmarks
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  luthor: ^0.5.2+1
  benchmark_harness: ^2.3.1
  acanthis: 
    path: ../
  vine: ^1.1.0
  

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
