name: acanthis
description: Acanthis is an easy-to-use validation library for Dart and Flutter.
version: 1.0.1
homepage: https://acanthis.serinus.app
documentation: https://acanthis.serinus.app/introduction.html
repository: https://github.com/francescovallone/acanthis

topics:
  - validation
  - dart
  - validation-form
  - validators


environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  email_validator: ^3.0.0
  crypto: ^3.0.0
  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
